using System;
using System.Collections.Generic;
using UnityEditor.Experimental.GraphView;
using UnityEngine;

namespace LUP.PCR
{
    //RequireComponent(typeof(Animator))]
    public class WorkerAI : MonoBehaviour
    {
        public WorkerBlackboard LocalBlackboard { get; private set; }

        // РЬКЅЦЎ (UI Ею ПмКЮПЁМ­ БИЕЖПы)
        public event Action<WorkerAI> OnEatCompleted;    
        public event Action<WorkerAI> OnTaskStarted;     // [РлОї НУРл]
        public event Action<WorkerAI> OnTaskFinished;    // [РлОї ПЯЗс]
        
        BTNode root;
        Worker worker;
        
        public float hunger = 0.5f;

        // bool isWorking, bool isEating ЕюРК State ХЌЗЁНКПЁМ­ АЁСЎПРАд ЧвБю АэЙЮСп
        // hasNewTask, isTaskPaused ЕюЕЕ State ХЌЗЁНКПЁМ­ АЁСЎПРАд ЧвБю АэЙЮСп
        public bool isWorking = false; 
        public bool isEating = false;
        public bool hasNewTask = false;
        public bool hasPausedWork = false;

        public Vector3 originSpot;
      
        public void StartTask()
        {
            isWorking = true;
            OnTaskStarted?.Invoke(this);
        }

        public void FinishTask()

        {
            isWorking = false;
            OnTaskFinished?.Invoke(this);

        }


        //public void MoveTo(TileInfo buiding)
        //{
        //   // transform.position = Vector3.MoveTowards(transform.position, tile.pos, Time.deltaTime * 2f);
        //}

        //public bool IsAt(BuildingData tile)
        //{
        //    //return Vector3.Distance(transform.position, tile.place) < 0.1f;
        //}

        private void Awake()
        {
            worker = GetComponent<Worker>();

            // [ЧйНЩ 2] КэЗЂКИЕх РЮНКХЯНК Л§МК
            LocalBlackboard = new WorkerBlackboard();
        }

        private void Start()
        {
            //СЄРћ ЕЅРЬХЭ(ТќСЖ) ЕюЗЯ
            LocalBlackboard.SetValue(BBKeys.Self, worker);
            LocalBlackboard.SetValue(BBKeys.OwnerAI, this); // ActionNodeПЁМ­ РЬКЅЦЎ ШЃУт НУ ЧЪПф

            // BT ЦЎИЎ БИМК
            SettingBT();
        }
        
        void SettingBT()
        {
            // И№Еч Leaf Node Л§МКРкПЁ LocalBlackboardИІ РќДо (СжРд)
            // CompositeNode(Sequence/Selector)ДТ КэЗЂКИЕхАЁ ЧЪПф ОјРИЙЧЗЮ ИЎНКЦЎИИ РќДо

            // Sequence: ЙшАэЧФ УГИЎ
            BTNode hungerSequence = new SequenceNode(new List<BTNode>
         {
             new IsHealthLowChecker(LocalBlackboard),
             new GoToEatingPlace(LocalBlackboard),
             new EatFood(LocalBlackboard),
            // new GoBackToOriginPosition()
         });

            // Sequence: ЧЯДј РЯ РчАГ
            BTNode resumeTaskSequence = new SequenceNode(new List<BTNode>
        {
            new IsPausedTaskChecker(LocalBlackboard),
            new GoToPausedTaskLocation(LocalBlackboard),
            new ResumePausedTask(LocalBlackboard)
        });

            // Sequence: Лѕ РЯ НУРл
            BTNode newTaskSequence = new SequenceNode(new List<BTNode>
        {
            new IsNewTaskChecker(LocalBlackboard),
            new GoToNewTaskLocation(LocalBlackboard),
            new StartNewTask(LocalBlackboard)
        });

            // Selector: РлОї/ШоНФ
            BTNode taskSelector = new SelectorNode(new List<BTNode>
           {
               resumeTaskSequence,
               newTaskSequence,
               new GoToLounge(LocalBlackboard)
           });

            // Root Selector: ЙшАэЧФ Ёц РлОї/ШоНФ
            root = new SelectorNode(new List<BTNode>
            {
                hungerSequence,
                taskSelector
            });

        }

        private void Update()
        {
            if (root == null) return;

            // [ЧйНЩ 5] ЕПРћ ЕЅРЬХЭ ЕПБтШ­ (Sync)
            // WorkerAIРЧ КЏМі АЊРЬ ЙйВюИщ -> КэЗЂКИЕхЕЕ СяНУ ОїЕЅРЬЦЎЕЪ
            // BT ГыЕхЕщРК КЏМіИІ СїСЂ ОШ КИАэ КэЗЂКИЕхРЧ KeyИИ КН
            LocalBlackboard.SetValue(BBKeys.Hunger, hunger);
            LocalBlackboard.SetValue(BBKeys.IsWorking, isWorking);
            LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);
            LocalBlackboard.SetValue(BBKeys.HasPausedTask, hasPausedWork);

            root.Evaluate();
        }



    }

}