using System;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

namespace LUP.PCR
{
    [RequireComponent(typeof(Worker))]
    [RequireComponent(typeof(UnitMover))]
    public class WorkerAI : MonoBehaviour
    {
        [Header("State")]
        [SerializeField] private float hunger = 0;
        private bool isHunger = false;
        private bool isWorking = true; 
        //private bool hasNewTask = false;

        [Header("Component")]
        private Worker worker;
        private UnitMover mover;
        private BTNode root;

        private void OnEnable()
        {
            // @TODO : ΫΧ±έ≈φάΗΖΈ ±≥ΟΦ«œ±β
            WorkerDataCenter dataCenter = this.transform.root.GetComponent<WorkerDataCenter>();

            if(dataCenter != null)
            {
                dataCenter.RegisterWorker(this);
            }
        }

        //@TODO: BuildingSystemΩΓ ά÷¥¬ Ϋ«ΝΠ currBuildings ΙΉ Α«ΙΑ≈Ηά‘IDΖΈ Α«ΙΑ ΝΕ»Η«ΊΦ≠ entrancePos ΝΔ±Ό«œ±β.
        // Νω±ίάΚ ά”ΫΟΖΈ Α«ΙΑ «ΝΗ°Τ’ άΎΟΦΩΓΦ≠ ΝςΝΔ entrancePos ΗΠ ΑΓΝ°Ω¬¥Ό.
        [Header("Task")]
        private ProductableBuilding currentTaskBuilding = null;
        [SerializeField] private ProductableBuilding restaurantBuilding = null;
        [SerializeField] private ProductableBuilding workerStationBuilding = null;

        // 
        public WorkerBlackboard LocalBlackboard { get; private set; }
        public float Hunger
        {
            get => hunger;
            set
            {
                hunger = value;
                LocalBlackboard.SetValue(BBKeys.Hunger, hunger);

                CheckHungerState();
            }
        }
        private void CheckHungerState()
        {
            bool shouldBeHungry = hunger >= HungerRules.HungryThreshold;

            if (isHunger != shouldBeHungry)
            {
                IsHunger = shouldBeHungry;
            }
        }

        public bool IsHunger
        {
            get => isHunger;
            set
            {
                isHunger = value;
                LocalBlackboard.SetValue(BBKeys.IsHunger, isHunger);
            }
        }

        public bool IsWorking
        {
            get => isWorking;
            set
            {
                isWorking = value;
                LocalBlackboard.SetValue(BBKeys.IsWorking, isWorking);
            }
        }
        
        public void InitBTReferences()
        {
            worker = GetComponent<Worker>();
            mover = GetComponent<UnitMover>();
            LocalBlackboard = new WorkerBlackboard();

            InitBlackboard();
            CheckHungerState();
            SettingBT();
        }

        private void InitBlackboard()
        {
            //ΝΛάϊ ΒΞάΧ≈Ά(¬ϋΝΕ) ΒνΖœ
            LocalBlackboard.SetValue(BBKeys.OwnerAI, this);
            LocalBlackboard.SetValue(BBKeys.Self, worker);
            LocalBlackboard.SetValue(BBKeys.UnitMover, mover);

            // BT Μσ≈¬ Ο ±β»≠
            LocalBlackboard.SetValue(BBKeys.Hunger, hunger);
            LocalBlackboard.SetValue(BBKeys.IsHunger, IsHunger);

            // Α«ΙΑ ΜΐΦΚΒ«¥¬ ΫΟΝΓΚΈ≈Ά άΎΒΩάΗΖΈ Ο ±β»≠Β… άßΡΓ : ΫΡ¥γ, άέΨς ΫΚ≈ΉάΧΦ«
            LocalBlackboard.SetValue<BuildingBase>(BBKeys.Restaurant, restaurantBuilding);
            LocalBlackboard.SetValue<BuildingBase>(BBKeys.WorkerStation, workerStationBuilding);

            // @TODO : currentTaskBuildingάΜ ΙόάΜ AssignTask()ΗΠ ΨνΒπΦ≠ »ΘΟβ«œΑ‘ «“Νω ΜΐΑΔ«œ±β
            // ΩωΡΩ ΫΟάέ άßΡΓ : ΕσΩνΝω
           // currentTaskBuilding = workerStationBuilding;
           // LocalBlackboard.SetValue<BuildingBase>(BBKeys.AssignedWorkplace, currentTaskBuilding); 
           // LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);
           LocalBlackboard.SetValue(BBKeys.IsWorking, isWorking);

        }

        void SettingBT()
        {
            // ΗπΒγ Leaf Node ΜΐΦΚάΎΩΓ LocalBlackboardΗΠ άϋ¥ό (Ν÷ά‘)
            // CompositeNode(Sequence/Selector)¥¬ ΚμΖΔΚΗΒεΑΓ « Ωδ ΨχάΗΙ«ΖΈ Η°ΫΚΤ°ΗΗ άϋ¥ό

            // Sequence: ΙηΑμ«Ρ Ο≥Η°
            BTNode hungerSequence = new SequenceNode(new List<BTNode>
         {
             new IsHealthLowChecker(LocalBlackboard),
             new PauseCurrentTask(LocalBlackboard),
             new GoToEatingPlace(LocalBlackboard),
             new EatFood(LocalBlackboard),
         });

        // Sequence: Μθ άœ ΫΟάέ
        BTNode workingSequence = new SequenceNode(new List<BTNode>
        {
            new IsNewTaskChecker(LocalBlackboard),
            new GoToNewTaskLocation(LocalBlackboard),
            new StartNewTask(LocalBlackboard)
        });

        // Root Selector: ΙηΑμ«Ρ Γφ άέΨς/»όΫΡ
        root = new SelectorNode(new List<BTNode>
        {
            hungerSequence,
            workingSequence,
            new GoToWorkerStation(LocalBlackboard)
        });
        }

        public void UpdateBT()
        {
            if (root == null) return;
            root?.Evaluate();

            if(!isHunger)
            {
                // ΙηΑμ«ΝΑ‘ ΗΗΒι±β
                Hunger = Mathf.Clamp(hunger + Time.deltaTime * 0.1f, 0, 3);
            }
        }

        //@TODO : AssignTask()ΗΠ ΨνΒπΦ≠ ΨνΕΜΑ‘ »ΘΟβ«œΑ‘ «“Νω ΜΐΑΔ«œ±β
        // Νω±ίάΚ ά”ΫΟΖΈ ΙωΤΑUI OnClick(ΙΧΗ° ΩάΚξΝßΤ° άΎΟΦΗΠ ΝωΝΛ)άΗΖΈ Α«ΙΑ άßΡΓΑΓ ΝωΝΛΒ«Α‘ «Ώ¥Ό.
        public void AssignTask(ProductableBuilding building)
        {
           // CancelOrReplaceCurrentTask();
            currentTaskBuilding = building;
            //HasNewTask = true;
            //LocalBlackboard.SetValue(BBKeys.HasNewTask, true);
            LocalBlackboard.SetValue(BBKeys.AssignedWorkplace, currentTaskBuilding);
        }
    }

}